baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "Ruibo's Blog"
theme = "PaperMod"

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
ShowReadingTime = true
ShowToc = true
ShowCodeCopyButtons = true

[params.homeInfoParams]
Title = "Hi, I’m Ruibo"
Content = "My learning notes. Let's learn together!"

[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 10

[[menu.main]]
name = "Search"
url = "/search/"
weight = 20

[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 30


[caches]
  [caches.images]
    dir = ':cacheDir/images'
