baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "Ruibo's Library"
theme = "PaperMod"

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
mainSections = ["posts", "topics", "devlogs"]
ShowReadingTime = true
ShowToc = true
ShowCodeCopyButtons = true

[params.homeInfoParams]
Title = "Read, Build, Think."
Content = "RBT on the way. Latest posts update in X."

[[params.socialIcons]]
name = "X"          # PaperMod’s icon name (works for X too)
url  = "https://x.com/ruibo_ml"
# optional:
title = "Update latest posts on X"

[[params.socialIcons]]
name = "googlescholar"
url  = "https://scholar.google.com/citations?user=auIx_r0AAAAJ&hl=en&oi=ao"

[[params.socialIcons]]
name = "github"
url  = "https://github.com/TURuibo"

[[menu.main]]
name = "Topics"
url = "/topics/"
weight = 10

[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 20

[[menu.main]]
name = "Devlogs"
url = "/devlogs/"
weight = 30

[[menu.main]]
name = "Search"
url = "/search/"
weight = 40

[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 50

[caches]
  [caches.images]
    dir = ':cacheDir/images'
