baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "Ruibo's Library"
theme = "PaperMod"

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
mainSections = ["posts", "topics", "devlogs"]
ShowReadingTime = true
ShowToc = true
ShowCodeCopyButtons = true

[params.homeInfoParams]
Title = "Read, Build, Think."
Content = "R.B.T. in progress ..."

[[menu.main]]
name = "Topics"
url = "/topics/"
weight = 10

[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 20

[[menu.main]]
name = "Devlogs"
url = "/devlogs/"
weight = 30

[[menu.main]]
name = "Search"
url = "/search/"
weight = 40

[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 50

[caches]
  [caches.images]
    dir = ':cacheDir/images'
